### PR TITLE
Create How to replace icon in linux

### PR DESCRIPTION
**Pull request by imshaiknasir**

### CODE REVIEW

**Comment by dhanishgajjar** [comment]
@imshaiknasir Can you check the app I linked in the README for linux?

**Comment by imshaiknasir** [comment]
Yes Sir,
I checked the link you provided in "READ ME" section.
But that requires a 3rd party software to be installed, than the process can done. (Its the safe way) :slightly_smiling_face: 

An user would just copy and paste the content rather than installing a software. (Its a nerd way) :nerd_face: 

Both ways are fine. :+1:

**Comment by sushant-j** [comment]
This is quite straightforward. I really like this way! 
@dhanishgajjar - Is it possible to add this as an alternate way in instructions for Linux?

**Comment by sushant-j** [comment]
@imshaiknasir  - Although this way is really straightforward and simple, it replaces only the icon in Ubuntu Launcher, not in the App Switcher (which comes when you cycle apps through Alt + Tab). 
Do you have any idea where VSCode refers for that icon?

**Comment by imshaiknasir** [comment]
Hello @sushant-j ,
Dear, I don't think that there's any issue while app switching (i.e, Alt + Tab)  ( Proof: Screenshot below). And I totally agree with @dhanishgajjar Sir's provided link. Mine is an alternative.
I've tested in 3 linux distros (kali , ubuntu, fedora). I haven't faced any kind of problem yet. And as per the knowledge I'm pretty sure, which path VS Code uses for its icon.
If I'm misleading, than let me know the exact path! :slightly_smiling_face: 
screenshot from 2017-11-18 00-01-32

**Pull request closed without merging**
