### PR TITLE
Add additional icons

### PR DESCRIPTION
**Pull request by fnky**
Adds additional colored icons such as:

- White on Black
- Black on White
- Batgirl
- Office 2017 (The brand, Word, Excel, Powerpoint, Outlook OneNote)
- FrontPage and legacy Outlook
- Spotify
- Neon — a custom one :)

### CODE REVIEW

**Comment by fnky** [comment]
Note that I haven't generated ICNS/ICO formats yet. Give me a moment :)

**Comment by fnky** [comment]
Added ICNS and ICO formats :+1:

**Comment by roboflank** [comment]
@fnky How do you generate the PNG formats and ICO?
I also have some additions.

**Comment by denzelwamburu** [comment]
@fnky How do you generate the PNG formats and ICO?
I also have some additions.

**Comment by dhanishgajjar** [comment]
Hey @fnky sorry, I changed the files a lot, but I liked some of the icons you created and I have put them on the project, I also have mentioned you in Contributions :) I am still fixing a lot of things and I will update you soon :) Thank you

**Comment by fnky** [comment]
@denzelwamburu I used Icon Slate for generating ICNS and ICO and exported PNGs from Sketch.

@dhanishgajjar Thanks!

**Pull request closed without merging**
